import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'
import { tailwindPlugin } from './tailwind-plugin.mjs'

const root = dirname(fileURLToPath(import.meta.url))
const src = join(root, 'src')
const modsDir = join(src, 'mods')

// Registration is the directory listing: every src/mods/*.tsx is a mod, in filename order.
// index.ts is generated so config.tsx has a static import to typecheck and bundle.
export async function writeModsIndex() {
	const names = (await readdir(modsDir)).filter(name => /\.tsx?$/.test(name) && name !== 'index.ts').map(name => name.replace(/\.tsx?$/, '')).sort()
	const contents = [
		'// Generated by build.mjs from the files in this directory. Do not edit.',
		"import type { Mod } from '@/mod'",
		...names.map((name, i) => `import * as m${i} from './${name}'`),
		`export const mods: Mod[] = [${names.map((_, i) => `m${i}`).join(', ')}]`,
		'',
	].join('\n')
	const target = join(modsDir, 'index.ts')
	if (await readFile(target, 'utf8').catch(() => null) !== contents) await writeFile(target, contents)
	return names
}

// One document-script bundle. React, its JSX runtime, and tldraw stay external so the script binds to the app's own instances.
export const buildOptions = {
	entryPoints: [join(src, 'config.tsx')],
	bundle: true,
	format: 'esm',
	platform: 'browser',
	jsx: 'automatic',
	alias: { '@': src },
	external: ['react', 'react-dom', 'react-dom/client', 'react/jsx-runtime', 'tldraw'],
	plugins: [tailwindPlugin({ sources: [src] })],
	define: { 'process.env.NODE_ENV': '"production"' },
	loader: { '.png': 'dataurl' },
}

export async function bundle() {
	await writeModsIndex()
	const result = await build({ ...buildOptions, write: false, logLevel: 'warning' })
	return result.outputFiles[0].contents
}

// `node build.mjs`: bundle without an open document, as a syntax and import check.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
	const names = await writeModsIndex()
	const out = await bundle()
	console.log(`bundle ok: ${names.length} mods (${names.join(', ') || 'none'}) → ${out.length} bytes`)
}
